export interface chapterTypes {
  id: number;
  title: string;
  time: number;
  isCompleted: boolean;
  isUnlocked: boolean;
  fromTime: number;
  toTime: number;
}

export interface Chapters {
  areAutoGenerated: boolean;
  chapters: chapterTypes[];
}

export interface VideoData {
  id: string;
  duration: number;
  title: string;
  chapters: Chapters;
}

export interface courseData {
  id: number;
  duration: number;
  title: string;
  chapters: number;
  completed: number;
  videoId: string;
}

export interface PlaylistDetails {
  id: string;
  title: string;
}

export interface Item {
  id: string;
  title: string;
  isCompleted: boolean;
}

export interface PlaylistData {
  playlistDetails: PlaylistDetails;
  items: Item[];
  totalResults: number;
}

export interface playList {
  id: string;
  title: string;
  chapters: number;
  completed: number;
}
