export interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

export interface Chapter {
  title: string;
  time: number;
  thumbnails: Thumbnail[];
  isCompleted: boolean;
  isUnlocked: boolean;
}

export interface Chapters {
  areAutoGenerated: boolean;
  chapters: Chapter[];
}

export interface VideoData {
  id: string;
  duration: number;
  title: string;
  chapters: Chapters;
}

export interface courseData {
  id: number;
  duration: number;
  title: string;
  chapters: number;
  completed: number;
  videoId: string;
}
