import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatTime(time: number) {
  const minutes = Math.floor(time / 60);
  const seconds = time % 60;
  const hours = Math.floor(minutes / 60);
  const minutesFormatted = minutes % 60;
  const secondsFormatted = seconds < 10 ? "0" : "";
  return `${hours}:${
    minutesFormatted < 10 ? "0" : ""
  }${minutesFormatted}:${secondsFormatted}${seconds}`;
}

export async function getVideoInfo(id: string, options = { chapters: true }) {
  const json = await getJSONFromHTML(`https://www.youtube.com/watch?v=${id}`);
  let result: any = { id };
  // Get total duration
  result.title =
    json.contents.twoColumnWatchNextResults.results.results.contents[0].videoPrimaryInfoRenderer.title.runs[0].text;

  result.duration =
    json.frameworkUpdates.entityBatchUpdate.mutations[0].payload
      .macroMarkersListEntity.markersList.markers[0].durationMillis / 10;

  if (options.chapters) {
    let chapters = [];
    let areAutoGenerated = false;

    const engagementPanel = json.engagementPanels?.find(
      (panel: any) =>
        panel.engagementPanelSectionListRenderer?.content
          ?.macroMarkersListRenderer
    );

    const contents =
      engagementPanel?.engagementPanelSectionListRenderer?.content
        ?.macroMarkersListRenderer?.contents;

    if (contents) {
      areAutoGenerated = "macroMarkersInfoItemRenderer" in contents[0];
      const relevantContents = contents.slice(areAutoGenerated ? 1 : 0);

      chapters = relevantContents.map((chapter: any) => {
        const chapterData = chapter.macroMarkersListItemRenderer;
        const timeInt = getIntFromDuration(
          chapterData.timeDescription.simpleText
        );

        return {
          title: chapterData.title.simpleText,
          time: timeInt,
        };
      });
    }
    result.chapters = {
      areAutoGenerated,
      chapters,
    };
  }
  return result;
}

// Helper Functions

async function getJSONFromHTML(url: string) {
  const response = await fetch(url, { cache: "no-store" });
  const html = await response.text();
  const scriptContent = extractScriptContent(html, "ytInitialData");
  return JSON.parse(scriptContent);
}

function getIntFromDuration(timeStr: string) {
  const isNegative = timeStr[0] === "-";
  if (isNegative) {
    timeStr = timeStr.slice(1);
  }

  const timeParts = timeStr.split(":").map((part) => parseInt(part, 10));
  let seconds = 0;

  switch (timeParts.length) {
    case 3: // hours:minutes:seconds
      seconds = timeParts[0] * 3600 + timeParts[1] * 60 + timeParts[2];
      break;
    case 2: // minutes:seconds
      seconds = timeParts[0] * 60 + timeParts[1];
      break;
    case 1: // seconds
      seconds = timeParts[0];
      break;
    default:
      throw new Error("Invalid time format");
  }

  return isNegative ? -seconds : seconds;
}

export function extractScriptContent(html: string, variableName: string) {
  const regex = new RegExp(`var ${variableName} = (.+?);<\/script>`);
  const match = html.match(regex);
  if (match && match[1]) {
    return match[1];
  }
  throw new Error("Could not find script data");
}

export async function getPlaylistInfo(id: string) {
  const json = await getJSONFromHTML(
    `https://www.youtube.com/playlist?list=${id}`
  );
  let result: any = { id };

  // Get total duration
  const playlistDetails = json.playlistSidebarRenderer;
  if (playlistDetails) {
    result.duration = parseInt(playlistDetails.videoCountText.runs[0].text, 10);
    result.title = playlistDetails.title.simpleText;
  }

  return result;
}

export function convertSecondsToHours(seconds: number) {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const remainingSeconds = seconds % 60;
  return `${hours}:${minutes < 10 ? "0" : ""}${minutes}:${
    remainingSeconds < 10 ? "0" : ""
  }${remainingSeconds}`;
}
