import { VideoData } from "@/types";

function parseDurationToSeconds(durationStr: string): number {
  if (!durationStr) return 0;
  if (!durationStr.includes(":")) {
    const seconds = parseInt(durationStr, 10);
    return isNaN(seconds) ? 0 : seconds;
  }

  const parts = durationStr.split(":").map(Number);
  if (parts.length === 3) {
    return parts[0] * 3600 + parts[1] * 60 + parts[2];
  }
  if (parts.length === 2) {
    return parts[0] * 60 + parts[1];
  }
  return 0;
}

function parseChaptersFromDescription(
  description: string
): { title: string; time: number }[] {
  const chapters: { title: string; time: number }[] = [];
  const regex = /(\d{1,2}:\d{2}(?::\d{2})?)\s+(.*)/g;
  let match;

  while ((match = regex.exec(description)) !== null) {
    const timeStr = match[1];
    let title = match[2].trim();
    if (title.startsWith("-") || title.startsWith("–")) {
      title = title.substring(1).trim();
    }

    const time = parseDurationToSeconds(timeStr);
    chapters.push({ title, time });
  }
  return chapters;
}

export async function getVideoInfo(id: string): Promise<VideoData> {
  console.log("Fetching video info for", id);
  const videoId =
    id.startsWith("http") && id.includes("v=")
      ? id.split("v=")[1].split("&")[0]
      : id;

  const url = `https://www.youtube.com/watch?v=${videoId}`;

  try {
    const response = await fetch(url, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      },
    });
    const html = await response.text();

    const playerResponseStart = "var ytInitialPlayerResponse = ";
    const startIndex = html.indexOf(playerResponseStart);

    if (startIndex === -1) {
      throw new Error(
        "Could not find ytInitialPlayerResponse in the HTML. YouTube's structure may have changed."
      );
    }

    const jsonStartIndex = startIndex + playerResponseStart.length;

    const playerResponseEnd = "};";
    const endIndex = html.indexOf(playerResponseEnd, jsonStartIndex);

    if (endIndex === -1) {
      throw new Error("Could not find the end of ytInitialPlayerResponse.");
    }

    const jsonString = html.substring(jsonStartIndex, endIndex + 1);

    let data;
    try {
      data = JSON.parse(jsonString);
    } catch (e) {
      console.warn("Direct JSON extraction failed", e);
      throw new Error("Failed to parse YouTube data JSON");
    }

    const videoDetails = data.videoDetails;
    if (!videoDetails) {
      throw new Error("Video details not found in YouTube data");
    }

    const title = videoDetails.title;
    const description =
      videoDetails.shortDescription || videoDetails.description || "";

    const durationSeconds = parseInt(videoDetails.lengthSeconds, 10) || 0;

    const chaptersList = parseChaptersFromDescription(description);

    const responseData: VideoData = {
      id: videoId,
      duration: durationSeconds,
      title: title,
      chapters: {
        areAutoGenerated: false,
        chapters: chaptersList.map((c) => ({
          title: c.title,
          time: c.time,
          thumbnails: [],
          isCompleted: false,
          isUnlocked: false,
        })),
      },
    };

    return responseData;
  } catch (error) {
    console.error("Scraping failed:", error);
    throw error;
  }
}
