import { google } from "@ai-sdk/google";
import { generateObject } from "ai";
import { z } from "zod";
import { VideoData } from "@/types";

// Helper to parse duration string "HH:MM:SS" or "MM:SS" to seconds
function parseDurationToSeconds(durationStr: string): number {
  if (!durationStr) return 0;
  const parts = durationStr.split(":").map(Number);
  if (parts.length === 3) {
    return parts[0] * 3600 + parts[1] * 60 + parts[2];
  }
  if (parts.length === 2) {
    return parts[0] * 60 + parts[1];
  }
  return 0;
}

export async function getVideoInfo(id: string) {
  console.log("Fetching video info for", id);
  const url = id.startsWith("http")
    ? id
    : `https://www.youtube.com/watch?v=${id}`;

  const { object } = await generateObject({
    model: google("gemini-2.5-flash"),
    system: `You are a helpful assistant that can answer questions and help with tasks.
          I want you to get all app chapters of this video with timestamps, the total duration of the video, and the video title.
          Return the data in a JSON object with the following structure:
          {
            "title": "Video Title",
            "duration": "HH:MM:SS" or "MM:SS",
            "chapters": [
              {
                "title": "Chapter 1",
                "start": "00:00",
                "end": "00:00"
              }
            ]
          }
          Only return the JSON object, no other text or explanation. If you cannot find the chapters, return an empty chapters array but still try to get title and duration.
          `,
    prompt: url,
    schema: z.object({
      title: z.string(),
      duration: z.string(),
      chapters: z.array(
        z.object({
          title: z.string(),
          start: z.string(),
          end: z.string(),
        })
      ),
    }),
  });

  // Map to VideoData type
  const totalDuration = parseDurationToSeconds(object.duration);

  const chapters = object.chapters.map((ch) => ({
    title: ch.title,
    time: parseDurationToSeconds(ch.start),
    thumbnails: [], // Placeholder as AI doesn't yield thumbnails yet
    isCompleted: false,
    isUnlocked: false,
  }));

  const videoId =
    id.startsWith("http") && id.includes("v=")
      ? id.split("v=")[1].split("&")[0]
      : id;

  const responseData: VideoData = {
    id: videoId,
    duration: totalDuration,
    title: object.title,
    chapters: {
      areAutoGenerated: true,
      chapters: chapters,
    },
  };

  return responseData;
}
