import { VideoData, Chapter } from "@/types";

const apiKey = process.env.YOUTUBE_API_KEY;

// Parse ISO 8601 duration format (PT1H30M15S) to seconds
function parseISO8601Duration(isoDuration: string): number {
  if (!isoDuration || !isoDuration.startsWith("PT")) return 0;

  const regex = /PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/;
  const match = isoDuration.match(regex);

  if (!match) return 0;

  const hours = parseInt(match[1] || "0", 10);
  const minutes = parseInt(match[2] || "0", 10);
  const seconds = parseInt(match[3] || "0", 10);

  return hours * 3600 + minutes * 60 + seconds;
}

function parseDurationToSeconds(durationStr: string): number {
  if (!durationStr) return 0;
  if (!durationStr.includes(":")) {
    const seconds = parseInt(durationStr, 10);
    return isNaN(seconds) ? 0 : seconds;
  }

  const parts = durationStr.split(":").map(Number);
  if (parts.length === 3) {
    return parts[0] * 3600 + parts[1] * 60 + parts[2];
  }
  if (parts.length === 2) {
    return parts[0] * 60 + parts[1];
  }
  return 0;
}

function parseChaptersFromDescription(
  description: string
): { title: string; time: number }[] {
  const chapters: { title: string; time: number }[] = [];
  const regex = /(\d{1,2}:\d{2}(?::\d{2})?)\s+(.*)/g;
  let match;

  while ((match = regex.exec(description)) !== null) {
    const timeStr = match[1];
    let title = match[2].trim();
    if (title.startsWith("-") || title.startsWith("–")) {
      title = title.substring(1).trim();
    }

    const time = parseDurationToSeconds(timeStr);
    chapters.push({ title, time });
  }
  return chapters;
}

export async function getVideoInfo(videoId: string) {
  if (!apiKey) {
    throw new Error("YouTube API key is required");
  }

  try {
    // YouTube Data API v3 endpoint
    const apiUrl = `https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails&id=${videoId}&key=${apiKey}`;

    const response = await fetch(apiUrl);

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        `YouTube API request failed: ${response.status} - ${
          errorData.error?.message || response.statusText
        }`
      );
    }

    const data = await response.json();

    if (!data.items || data.items.length === 0) {
      throw new Error("Video not found");
    }

    const item = data.items[0];
    const snippet = item.snippet;
    const contentDetails = item.contentDetails;

    // Extract title
    const title = snippet.title || "Unknown Title";

    // Extract description
    const description = snippet.description || "";

    // Extract duration (ISO 8601 format: PT1H30M15S)
    const isoDuration = contentDetails.duration;
    const duration = parseISO8601Duration(isoDuration);

    // Parse chapters from description
    const parsedChapters = parseChaptersFromDescription(description);

    // Transform chapters to match Chapter interface
    const chapters: Chapter[] = parsedChapters.map((chapter) => ({
      title: chapter.title,
      time: chapter.time,
      thumbnails: [], // Empty array since YouTube API doesn't provide chapter thumbnails
      isCompleted: false,
      isUnlocked: false,
    }));

    // Return VideoData structure
    return {
      id: videoId,
      title: title,
      duration: duration, // Return as number (seconds)
      chapters: {
        areAutoGenerated: false, // Chapters from description are not auto-generated
        chapters: chapters,
      },
    } as VideoData;
  } catch (error) {
    console.error("YouTube API request failed:", error);
    throw error;
  }
}
